### ISSUE TITLE
Modrinth/Modpack usage

### ISSUE THREAD

**Issue by alexstanleeee** [JerryLu086/Oooh-Pinky#2]
I'm so sorry for putting this on the issues tab on GitHub, but I was unsure where else to ask.
I love this mod, but is there any chance it could be uploaded to Modrinth so I can include it in my modpack?
Thanks so much

**Comment by JerryLu086** [comment]
https://modrinth.com/mod/oooh-pinky

**Comment by JerryLu086** [comment]
Ahhh wait, I just found that it doesn't have the files above 1.19. I'll upload them soon.

**Comment by JerryLu086** [comment]
Done, thanks for reminding me this lol
